name: DeviceAdvisor

on:
  push:
    branches:
      - "*"
      - "!main"

env:
  BUILDER_VERSION: v0.8.29
  BUILDER_SOURCE: releases
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-iot-device-sdk-cpp-v2
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DATEST_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DATEST_SECRET_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: us-east-1
  # env for Device Advisor
  DA_TOPIC: test/da
  DA_SHADOW_PROPERTY: datest
  DA_SHADOW_VALUE_SET: ON
  DA_SHADOW_VALUE_DEFAULT: OFF


jobs:
  windows-no-cpu-extensions:
    runs-on: windows-latest
    steps:
      - name: Run DA python script
        run: |
          md D:\a\work
          cd D:\a\work
          python -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz', 'builder.pyz')"
          python builder.pyz build -p ${{ env.PACKAGE_NAME }} build_da skip_samples
          echo 'da test starts...'
          python3 -m pip install boto3
          python deviceadvisor\script\run.py
